name: Docker Image CI

on:
  push:
    branches: [ master, test ]

env:
  DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: make build


  build-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_image_tag: ["3.8-slim", "3.9-slim", "3.10-slim", "3.11-slim", "3.12-slim"]
        poetry_version: ["1.6.1", "1.7.1", "1.8.2"]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: >
        make build-version \
          POETRY_VERSION=${{ matrix.poetry_version }} \
          PYTHON_IMAGE_TAG=${{ matrix.python_image_tag }}

    - name: Set Up jDK
      uses: actions/setup-java@v4
      with: 
        distribution: 'temurin'
        java-version: |
          8
          21